# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clisample < Formula
  desc ""
  homepage "https://github.com/kurageso/clisample"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.4/clisample_0.0.4_darwin_amd64.tar.gz"
      sha256 "82dbc90da864319a81b5073fe561201394fdf41735cacc6ea8be04ee3bb8a3c3"

      def install
        bin.install "program" => "clisample"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.4/clisample_0.0.4_darwin_arm64.tar.gz"
      sha256 "02576a2c2550656ed2ae75a6d5f2c07cd94fc934b7acf1ba4dac19ed021f81a6"

      def install
        bin.install "program" => "clisample"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.4/clisample_0.0.4_linux_arm64.tar.gz"
      sha256 "75559878479b47991b0d3a31a8d3ada410f7793c89b01487db04b1463d79de58"

      def install
        bin.install "program" => "clisample"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.4/clisample_0.0.4_linux_amd64.tar.gz"
      sha256 "db26a5efd66ab1caa186cf84fa37a2a4718b92c9818f53a2ee8e8eaccbdaee47"

      def install
        bin.install "program" => "clisample"
      end
    end
  end
end
