# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clisample < Formula
  desc ""
  homepage "https://github.com/kurageso/clisample"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.1/clisample_0.0.1_darwin_amd64.tar.gz"
      sha256 "a327882f673b7536f33ac0ca1dc50a0bfc1e14c52bf95a3cbff83d2a46d395be"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.1/clisample_0.0.1_darwin_arm64.tar.gz"
      sha256 "6ca0458be113eb33e42cb31c2ba3bf136a3bc5e4fea64edd93d69737c1f9b46c"

      def install
        bin.install "program"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.1/clisample_0.0.1_linux_arm64.tar.gz"
      sha256 "b8ad0335a65a29472fbd45607592de5e9a0364f6bd23f7a326198a89dc76a464"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/clisample/releases/download/v0.0.1/clisample_0.0.1_linux_amd64.tar.gz"
      sha256 "76cc4d20dcd9463e57923d4618bdee1db02065159b14219ead2906e7c1e3f221"

      def install
        bin.install "program"
      end
    end
  end
end
